/**
* This file is auto-generated by grpc-helper
*/

/* eslint-disable @typescript-eslint/no-namespace */

import * as grpc from '@midwayjs/grpc';

/* package hero start */
export namespace hero {
  export interface HeroService {
    findOne(data: HeroById): Promise<Hero>;
  }
  /**
   * HeroService client interface
   */
  export interface HeroServiceClient {
    findOne(options?: grpc.IClientOptions): grpc.IClientUnaryService<HeroById, Hero>;
  }
  export interface HeroById {
    id?: number;
  }
  export interface Hero {
    id?: number;
    name?: string;
  }
}
/* package hero end */
